/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#121317",
        "surface-container-highest": "#343539",
        "primary-fixed": "#d8e2ff",
        "background": "#121317",
        "secondary-container": "#3834b6",
        "surface-variant": "#343539",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#5b0015",
        "primary": "#adc6ff",
        "secondary-fixed": "#e2dfff",
        "on-background": "#e3e2e7",
        "error-container": "#93000a",
        "primary-container": "#4b8eff",
        "surface-bright": "#38393d",
        "on-tertiary-fixed": "#40000c",
        "on-tertiary-fixed-variant": "#920027",
        "on-surface-variant": "#c1c6d7",
        "on-secondary-container": "#b2b1ff",
        "on-secondary-fixed": "#0c006a",
        "primary-fixed-dim": "#adc6ff",
        "error": "#ffb4ab",
        "inverse-on-surface": "#2f3034",
        "surface-container-low": "#1a1b1f",
        "tertiary": "#ffb3b5",
        "on-primary-fixed": "#001a41",
        "on-primary-container": "#00285c",
        "secondary-fixed-dim": "#c2c1ff",
        "surface-container-lowest": "#0d0e12",
        "surface-tint": "#adc6ff",
        "on-tertiary": "#680019",
        "surface-container-high": "#292a2e",
        "inverse-surface": "#e3e2e7",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#004493",
        "tertiary-fixed": "#ffdada",
        "surface-container": "#1e1f23",
        "secondary": "#c2c1ff",
        "outline": "#8b90a0",
        "on-secondary": "#1c0b9f",
        "on-primary": "#002e69",
        "on-surface": "#e3e2e7",
        "tertiary-container": "#ff5167",
        "tertiary-fixed-dim": "#ffb3b5",
        "inverse-primary": "#005bc1",
        "outline-variant": "#414755",
        "surface": "#121317",
        "on-secondary-fixed-variant": "#3631b4"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "40px",
        "3xl": "48px",
        margin: "32px",
        gutter: "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", letterSpacing: "0", fontWeight: "400" }],
        "title-sm": ["20px", { lineHeight: "1.4", letterSpacing: "0", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "title-lg": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "zoom-in": "zoomIn 0.3s ease-out",
        "slide-up": "slideUp 0.3s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        zoomIn: {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
}